import {StyleSheet} from 'react-native';
import {WHITE, BLACK, PRIMARY, BACKGROUND} from 'styles/colors';
import {
  HS_10,
  HS_15,
  HS_20,
  MS_20,
  MS_45,
  VS_10,
  VS_100,
  VS_20,
  VS_30,
  VS_5,
  VS_50,
} from 'styles/mixins';

export const style = StyleSheet.create({
  mainContainer: {
    flex: 1,
  },
  upperContainer: {
    flexDirection: 'row',
    paddingHorizontal: HS_20,
    backgroundColor: PRIMARY,
    paddingTop: VS_20,
    paddingBottom: VS_50,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  lowerContainer: {
    backgroundColor: BACKGROUND,
    paddingHorizontal: HS_20,
    flex: 1,
  },
  searchInput: {
    backgroundColor: WHITE,
    fontSize: MS_20,
    flexGrow: 1,
    color: BLACK,
    width: '80%',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: HS_10,
    paddingHorizontal: HS_15,
    paddingVertical: VS_5,
    position: 'relative',
    bottom: VS_30,
    backgroundColor: WHITE,
    alignSelf: 'center',
    width: '90%',
  },
  iconContainer: {
    flexDirection: 'row',
    gap: HS_10,
    width: '20%',
  },
  arrowIcon: {
    position: 'absolute',
    left: HS_20,
    top: VS_20,
    alignSelf: 'center',
  },
  itemContainer: {
    marginVertical: VS_10,
    backgroundColor: WHITE,
    padding: HS_15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: HS_10,
  },
  fileIconContainer: {
    // backgroundColor: '#e2eafe',
    width: MS_45,
    height: MS_45,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: HS_10,
  },
  Fab: {
    position: 'absolute',
    margin: 16,
    right: 0,
    bottom: 0,
    backgroundColor: PRIMARY,
    borderRadius: VS_100,
  },
  itemInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: HS_10,
  },
});
